name: CMake

on:
  push:
    tags:
      - "v*.*"
      - "v*.*.*"

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install sfml dependency (Windows)
      if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest https://github.com/SFML/SFML/releases/download/3.0.0/SFML-3.0.0-windows-vc17-64-bit.zip -OutFile sfml.zip
        Expand-Archive sfml.zip -DestinationPath deps/sfml

    - name: Download ImGui dependency
      run: |
        git clone https://github.com/ocornut/imgui deps/imgui
        git clone https://github.com/eliasdaler/imgui-sfml deps/imgui-sfml
        git -C deps/imgui checkout docking
        cat deps/imgui-sfml/imconfig-SFML.h >> deps/imgui/imconfig.h

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSFML_DIR="${{github.workspace}}/deps/sfml/SFML-3.0.0/lib/cmake/SFML" -DSFML_INCLUDE_DIR="${{github.workspace}}/deps/sfml/SFML-3.0.0/include" -DSFML_LIB_DIR="${{github.workspace}}/deps/sfml/SFML-3.0.0/lib"

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 2

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/sim8051/src/Release/sim8051.exe
        body: "Automated release build."
